### ISSUE TITLE
[Feature]: Recompress posters & other media

### ISSUE THREAD

**Issue by ponchohoncho** [meisnate12/Plex-Image-Cleanup#18]
### Describe the Feature Request

I don't know if this is a great idea, but looking through the Metadata folder I see a lot of directories with >2mb images. I don't know that posters need to be that large on my TV or phone. I know that a lot of images I download from TPDB are 10mb each. If those aren't resized on upload, I'm sure that adds up too.

Would it make sense to iterate through what is there and recompress/resize/resample images to lower sizes or qualities?

**Comment by meisnate12** [comment]
That could be a thing but in my opinion outside the scoop of this project.
