### ISSUE TITLE
[Feature]: Support database vacuum

### ISSUE THREAD

**Issue by zhdenny** [meisnate12/Plex-Image-Cleanup#20]
### Describe the Feature Request

https://github.com/ChuckPa/PlexDBRepair

Above project has the ability to perform a "vacuum" on the database and perform a "Reindex" of the database. Can Plex-Image-Cleanup support this too?

Some documentation from Plex regarding Vacuum....and it appears that is what PlexDBRepair project is doing.
https://support.plex.tv/articles/repair-a-corrupted-database/

**Comment by meisnate12** [comment]
Probably could but in my opinion this function is outside the scope of this project.
