### ISSUE TITLE
Timeouts in Logs - Appears to not adhere to Timeout value set

### ISSUE THREAD

**Issue by kingwoftam** [meisnate12/Plex-Image-Cleanup#9]
### Version Number

1.0.0

### What branch are you on?

master

### Describe the Bug

Running PIC via Docker on MAC OS 10.15.7

When running Plex Image Cleanup, I continue to get timeout related errors that appear to occur after the default 600 seconds, even when I change the timeout value to a higher value.

Also appears to have run successfully but can't tell for sure.

Example log attached.

### Logs

https://gist.github.com/kingwoftam/20e6c5d5f2c18f1ef85a2617d05af718

**Comment by meisnate12** [comment]
It failed to connect to your plex to clean your db but it was able to clean the dir because it has file access
